server:
  port: 8081

google:
  client:
    Ids: 814606937527-v7tr5dfqegjijicq3jeu5arv5tcl4ks0.apps.googleusercontent.com,814606937527-kk7ooglk6pj2tvpn7ldip6g3b74f8o72.apps.googleusercontent.com

jwt:
  secret: testsecretisalsoasecret

datasource:
    url: jdbc:h2:/Users/rverma/test
    username: test
    password: