# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
        environment:
          TEST_DATABASE_URL: postgres://root@localhost/circle_test

      - image: circleci/postgres:9.5

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Install Postgres Client
          command: sudo apt install postgresql-client
      - run:
          name: Initialize DB Schema
          command: |
            psql \
            -d $TEST_DATABASE_URL \
            -f ~/repo/src/main/resources/schemas/psql-schema.sql
      - run:
          name: Validate Schema - List DB Tables
          command: |
            psql \
            -d $TEST_DATABASE_URL \
            -c "\d"

      - run:
          name: Maven Install
          command: mvn install
      - run:
          name: Maven Test
          command: |
            mvn test \
            -D spring.profiles.active=psql \
            -D spring.datasource.username=root \
            -D spring.datasource.url=jdbc:postgresql://localhost:5432/circle_test
